#include "domain_program.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "domain_reference_internal.h"

static uint32_t emit(ce_domain_program *p, uint32_t op, uint32_t a, uint32_t b, uint32_t aux, ce_complex v) {
    if (p->error[0]) return 0;
    for (uint32_t i = 0; i < p->count; ++i) {
        ce_domain_node n = p->nodes[i];
        if (n.op == op && n.a == a && n.b == b && n.aux == aux &&
            p->constants[i].re == v.re && p->constants[i].im == v.im) return i;
    }
    if (p->count == 8192) { strcpy(p->error, "Domain expression exceeds 8192 operations."); return 0; }
    uint32_t i = p->count++;
    p->nodes[i] = (ce_domain_node){op, a, b, aux}; p->constants[i] = v;
    return i;
}
static uint32_t cn(ce_domain_program *p, double re, double im) {
    return emit(p, DP_CONST, 0, 0, 0, (ce_complex){re, im});
}
static uint32_t cc(ce_domain_program *p, ce_complex v) { return cn(p, v.re, v.im); }
static uint32_t op(ce_domain_program *p, uint32_t kind, uint32_t a, uint32_t b) {
    if(kind==DP_ADD || kind==DP_MUL || kind==DP_SUB) {
        int ac=p->nodes[a].op==DP_CONST&&!p->nodes[a].aux;
        int bc=p->nodes[b].op==DP_CONST&&!p->nodes[b].aux;
        if(kind==DP_ADD&&ac&&p->constants[a].re==0&&p->constants[a].im==0)return b;
        if((kind==DP_ADD||kind==DP_SUB)&&bc&&p->constants[b].re==0&&p->constants[b].im==0)return a;
        if(kind==DP_MUL&&ac&&p->constants[a].re==1&&p->constants[a].im==0)return b;
        if(kind==DP_MUL&&bc&&p->constants[b].re==1&&p->constants[b].im==0)return a;
        /* Exact axis-aligned powers of two are rotations and exponent shifts.
           This applies to every expression, including constants introduced by
           primitive lowering; it does not approximate a multiplication. */
        if(kind==DP_MUL && (ac||bc)) {
            ce_complex v=p->constants[ac?a:b];
            double scalar=v.re!=0 && v.im==0?v.re:v.re==0?v.im:0;
            int exponent;
            if(isfinite(scalar) && scalar!=0 && frexp(fabs(scalar),&exponent)==0.5) {
                uint32_t quadrant=(v.im!=0?1:0)+(scalar<0?2:0);
                return emit(p,DP_DYADIC,ac?b:a,0,((uint32_t)(exponent-1+1074)<<2)|quadrant,(ce_complex){0,0});
            }
        }
    }
    return emit(p, kind, a, b, 0, (ce_complex){0,0});
}
static uint32_t an(ce_domain_program *p, uint32_t kind, uint32_t z, uint32_t order) {
    return emit(p, DP_ANALYTIC, z, order, kind, (ce_complex){0,0});
}
static uint32_t divn(ce_domain_program *p, uint32_t a, uint32_t b) { return op(p,DP_DIV,a,b); }
static uint32_t logn(ce_domain_program *p, uint32_t z, int active) {
    if (!active || p->config.function.branch_cut_angle == 3.14159265358979323846) return an(p,DA_LOG,z,0);
    /* pi is generated by the reference engine, rather than rounded to a C double. */
    uint32_t pi = emit(p, DP_CONST, 0, 0, 1, (ce_complex){0,0});
    uint32_t rotation = op(p,DP_MUL,cn(p,0,1),op(p,DP_SUB,pi,cn(p,p->config.function.branch_cut_angle,0)));
    return op(p,DP_SUB,an(p,DA_LOG,op(p,DP_MUL,z,an(p,DA_EXP,rotation,0)),0),rotation);
}
static uint32_t powr(ce_domain_program *p, uint32_t z, uint32_t w) {
    ce_domain_node n = p->nodes[w]; ce_complex v = p->constants[w];
    if (n.op == DP_CONST && !n.aux && v.im == 0 && floor(v.re) == v.re && fabs(v.re) <= 2147483647.0) {
        int64_t k = (int64_t)v.re; uint64_t t = k < 0 ? -k : k;
        uint32_t r = cn(p,1,0);
        while (t) { if (t & 1) r = op(p,DP_MUL,r,z); t >>= 1; if (t) z = op(p,DP_MUL,z,z); }
        return k < 0 ? an(p,DA_INV,r,0) : r;
    }
    return an(p,DA_EXP,op(p,DP_MUL,w,logn(p,z,1)),0);
}
static uint32_t function(ce_domain_program *, uint32_t, uint32_t, uint32_t);
static uint32_t map(ce_domain_program *,uint32_t,uint32_t,int);
static uint32_t expression(ce_domain_program *p, const ce_expression_instruction *code, uint32_t begin,
                           uint32_t end, uint32_t z, uint32_t c, const uint32_t *vars, uint32_t vc) {
    uint32_t stack[256], size = 0;
    if (end-begin > 256) { strcpy(p->error,"Domain expression stack limit exceeded."); return 0; }
    for (uint32_t i=begin;i<end && !p->error[0];++i) {
        ce_expression_instruction n=code[i]; uint32_t a=0,b=0,r=0;
        if (n.opcode == 0) r=cc(p,n.value);
        else if (n.opcode == 1) r=z;
        else if (n.opcode == 2) r=c;
        else if (n.opcode == 15) { if(n.argument>=vc) goto bad; r=vars[n.argument]; }
        else {
            if(!size) goto bad;
            a=stack[--size];
            switch(n.opcode) {
            case 8:r=op(p,DP_NEG,a,0);break;
            case 9:r=function(p,n.argument,a,c);break;
            case 10:r=op(p,DP_CONJ,a,0);break;
            case 11:r=an(p,DA_SQRT,op(p,DP_MUL,a,op(p,DP_CONJ,a,0)),0);break;
            case 12:r=op(p,DP_IMAG,logn(p,a,0),0);break;
            case 13:r=op(p,DP_REAL,a,0);break;
            case 14:r=op(p,DP_IMAG,a,0);break;
            case 16:case 24:r=emit(p,DP_TEST,a,a,n.opcode,(ce_complex){0,0});break;
            case 17:case 28:case 29:case 30:case 31:case 32:case 37:
                r=emit(p,DP_INTEGER,a,a,n.opcode,(ce_complex){0,0});break;
            case 25:case 26: {
                uint32_t alt=n.argument;
                if(alt<=i+1 || alt>end || code[alt-1].opcode!=27) goto bad;
                uint32_t done=code[alt-1].argument;
                if(done<alt || done>end) goto bad;
                b=expression(p,code,i+1,alt-1,z,c,vars,vc);
                uint32_t d=expression(p,code,alt,done,z,c,vars,vc);
                r=emit(p,DP_SELECT,a,n.opcode==25?b:d,n.opcode==25?d:b,(ce_complex){0,0});
                i=done-1;break;
            }
            case 33:case 34: {
                if(!n.argument || n.argument>size+1) goto bad;
                r=a;
                for(uint32_t j=1;j<n.argument;++j) {
                    b=stack[--size];
                    uint32_t t=emit(p,DP_TEST,r,b,n.opcode==33?20:22,(ce_complex){0,0});
                    r=emit(p,DP_SELECT,t,r,b,(ce_complex){0,0});
                }
                break;
            }
            case 38:
                r=op(p,DP_REAL,a,0);
                if(n.argument==2) { if(!size) goto bad; b=stack[--size]; r=op(p,DP_ADD,op(p,DP_REAL,b,0),op(p,DP_MUL,cn(p,0,1),r)); }
                else if(n.argument!=1) goto bad;
                break;
            case 40:r=map(p,a,a,0);break;
            case 41:r=an(p,DA_SQRT,a,0);break;
            default:
                if(!size) goto bad;
                b=a;a=stack[--size];
                if(n.opcode==3)r=op(p,DP_ADD,a,b);
                else if(n.opcode==4)r=op(p,DP_SUB,a,b);
                else if(n.opcode==5)r=op(p,DP_MUL,a,b);
                else if(n.opcode==6)r=divn(p,a,b);
                else if(n.opcode==7)r=powr(p,a,b);
                else if(n.opcode>=18 && n.opcode<=23)r=emit(p,DP_TEST,a,b,n.opcode,(ce_complex){0,0});
                else if(n.opcode==35 || n.opcode==36)r=emit(p,DP_INTEGER,a,b,n.opcode,(ce_complex){0,0});
                else if(n.opcode==39)r=an(p,DA_BESSEL,b,a);
                else goto bad;
            }
        }
        if(size>=256)goto bad;
        stack[size++]=r;
    }
    if(size==1)return stack[0];
 bad:strcpy(p->error,"Invalid domain expression program.");return 0;
}
static uint32_t function(ce_domain_program *p,uint32_t id,uint32_t z,uint32_t c) {
    const ce_function_config *f=&p->config.function;
    uint32_t one=cn(p,1,0),i=cn(p,0,1),a,b;
    switch(id) {
    case CE_FN_C:return c;
    case CE_FN_IDENTITY:return z;
    case CE_FN_SIN:return an(p,DA_SIN,z,0);
    case CE_FN_COS:return an(p,DA_COS,z,0);
    case CE_FN_TAN:return divn(p,function(p,CE_FN_SIN,z,c),function(p,CE_FN_COS,z,c));
    case CE_FN_SEC:return an(p,DA_INV,function(p,CE_FN_COS,z,c),0);
    case CE_FN_EXP:
        if(f->exp_base.re!=2.71828182845904523536 || f->exp_base.im!=0)z=op(p,DP_MUL,z,logn(p,cc(p,f->exp_base),0));
        return an(p,DA_EXP,z,0);
    case CE_FN_LN:
        a=logn(p,z,1);
        return f->log_base.re==2.71828182845904523536 && f->log_base.im==0?a:divn(p,a,logn(p,cc(p,f->log_base),0));
    case CE_FN_SINH:return op(p,DP_MUL,cn(p,0,-1),function(p,CE_FN_SIN,op(p,DP_MUL,i,z),c));
    case CE_FN_TANH:
        a=op(p,DP_MUL,i,z);return op(p,DP_MUL,cn(p,0,-1),divn(p,function(p,CE_FN_SIN,a,c),function(p,CE_FN_COS,a,c)));
    case CE_FN_ASIN:
        a=an(p,DA_SQRT,op(p,DP_SUB,one,op(p,DP_MUL,z,z)),0);
        return op(p,DP_MUL,cn(p,0,-1),logn(p,op(p,DP_ADD,op(p,DP_MUL,i,z),a),0));
    case CE_FN_ATAN:
        a=op(p,DP_MUL,i,z);
        return op(p,DP_MUL,cn(p,0,-0.5),op(p,DP_SUB,logn(p,op(p,DP_ADD,one,a),0),logn(p,op(p,DP_SUB,one,a),0)));
    case CE_FN_GAMMA:return an(p,DA_GAMMA,z,0);
    case CE_FN_LOG_GAMMA:return logn(p,an(p,DA_GAMMA,z,0),0);
    case CE_FN_BESSEL:return an(p,DA_BESSEL,z,cc(p,f->bessel_order));
    case CE_FN_ZETA:
        a=an(p,DA_ZETA,z,0);
        if(f->zeta_continuation)return a;
        b=emit(p,DP_TEST,op(p,DP_REAL,z,0),one,22,(ce_complex){0,0});
        return emit(p,DP_SELECT,b,a,emit(p,DP_CONST,0,0,2,(ce_complex){0,0}),(ce_complex){0,0});
    case CE_FN_POWER:return powr(p,z,cn(p,f->fractional_power,0));
    case CE_FN_MOBIUS:
        a=op(p,DP_ADD,op(p,DP_MUL,cc(p,f->mobius_a),z),cc(p,f->mobius_b));
        b=op(p,DP_ADD,op(p,DP_MUL,cc(p,f->mobius_c),z),cc(p,f->mobius_d));return divn(p,a,b);
    case CE_FN_POLYNOMIAL:
        if(!f->polynomial_count)return cn(p,0,0);a=cc(p,f->polynomial[f->polynomial_count-1]);for(uint32_t j=f->polynomial_count-1;j-->0;)a=op(p,DP_ADD,op(p,DP_MUL,a,z),cc(p,f->polynomial[j]));return a;
    case CE_FN_ALGEBRAIC:
        if(f->expression_count)z=expression(p,f->expression,0,f->expression_count,z,c,NULL,0);
        a=cn(p,0,0);
        for(uint32_t j=0;j<f->algebraic_term_count;++j) {
            const ce_algebraic_term *t=&f->algebraic_terms[j];b=cc(p,t->coefficient);
            if(t->factor_offset+t->factor_count>f->algebraic_factor_count){strcpy(p->error,"Invalid domain factors.");return 0;}
            for(uint32_t k=0;k<t->factor_count;++k) {
                const ce_algebraic_factor *fct=&f->algebraic_factors[t->factor_offset+k];uint32_t v=z;
                if(fct->chained_function_id>=0)v=function(p,fct->chained_function_id,v,c);
                v=function(p,fct->function_id,v,c);
                if(fct->power!=1)v=powr(p,v,cn(p,fct->power,0));
                if(fct->flags&1)v=an(p,DA_INV,v,0);
                if(fct->flags&2)v=function(p,CE_FN_LN,v,c);
                if(fct->flags&4)v=function(p,CE_FN_EXP,v,c);
                b=op(p,DP_MUL,b,v);
            }a=op(p,DP_ADD,a,b);
        }return a;
    default:strcpy(p->error,"Unknown domain function.");return 0;
    }
}
static uint32_t map(ce_domain_program *p,uint32_t z,uint32_t c,int dynamic) {
    const ce_map_config *f=&p->config;
    if(dynamic && f->dynamic_source_count) {
        uint32_t vars[256],r=cn(p,f->dynamic_reduction==2?1:0,0);
        if(f->dynamic_variable_count>256){strcpy(p->error,"Too many domain variables.");return 0;}
        for(uint32_t j=0;j<f->dynamic_source_count;++j) {
            for(uint32_t k=0;k<f->dynamic_variable_count;++k) {
                uint8_t flag=f->dynamic_variable_flags[k];
                vars[k]=flag==1?z:flag==2?op(p,DP_REAL,z,0):cc(p,f->dynamic_variables[j*f->dynamic_variable_count+k]);
            }
            uint32_t point=expression(p,f->dynamic_point_expression,0,f->dynamic_point_count,z,c,vars,f->dynamic_variable_count);
            for(uint32_t k=0;k<f->dynamic_variable_count;++k)if(f->dynamic_variable_flags[k]==3)vars[k]=point;
            uint32_t v=expression(p,f->dynamic_term_expression,0,f->dynamic_term_count,z,c,vars,f->dynamic_variable_count);
            /* The explicit dynamic skip policy is represented in the program. */
            if(f->dynamic_invalid_policy)v=emit(p,DP_SELECT,emit(p,DP_TEST,v,v,42,(ce_complex){0,0}),v,cn(p,f->dynamic_reduction==2?1:0,0),(ce_complex){0,0});
            r=f->dynamic_reduction==0?v:op(p,f->dynamic_reduction==1?DP_ADD:DP_MUL,r,v);
        }return r;
    }
    if(f->use_taylor) {
        z=op(p,DP_SUB,z,cc(p,f->taylor_center));uint32_t r=cn(p,0,0);
        for(uint32_t j=f->taylor_count;j-->0;)r=op(p,DP_ADD,op(p,DP_MUL,r,z),cc(p,f->taylor_coefficients[j]));
        return r;
    }
    return function(p,f->function_id,z,c);
}
ce_domain_program *ce_domain_compile(const ce_map_config *config) {
    if(!config)return NULL;
    ce_domain_program *p=calloc(1,sizeof(*p));if(!p)return NULL;p->config=*config;
    p->nodes=calloc(8192,sizeof(*p->nodes));p->constants=calloc(8192,sizeof(*p->constants));
    if(!p->nodes || !p->constants){ce_domain_program_free(p);return NULL;}
    op(p,DP_Z,0,0);op(p,DP_C,0,0);
    p->output=map(p,0,1,1);
    /* Remove unused compiler temporaries before either executor sees the graph. */
    uint8_t *used=calloc(p->count,1);uint32_t *index=calloc(p->count,sizeof(uint32_t));
    if(!used||!index){free(used);free(index);ce_domain_program_free(p);return NULL;}
    used[0]=used[1]=used[p->output]=1;
    for(uint32_t j=p->count;j-->2;)if(used[j]) {
        ce_domain_node n=p->nodes[j];
        if(n.op!=DP_CONST)used[n.a]=1;
        if(n.op==DP_ADD||n.op==DP_SUB||n.op==DP_MUL||n.op==DP_DIV||n.op==DP_TEST||n.op==DP_INTEGER||n.op==DP_SELECT||(n.op==DP_ANALYTIC&&n.aux==DA_BESSEL))used[n.b]=1;
        if(n.op==DP_SELECT)used[n.aux]=1;
    }
    uint32_t total=0;
    for(uint32_t j=0;j<p->count;++j)if(used[j]) {
        ce_domain_node n=p->nodes[j];index[j]=total;
        if(n.op!=DP_CONST)n.a=index[n.a];
        if(n.op==DP_ADD||n.op==DP_SUB||n.op==DP_MUL||n.op==DP_DIV||n.op==DP_TEST||n.op==DP_INTEGER||n.op==DP_SELECT||(n.op==DP_ANALYTIC&&n.aux==DA_BESSEL))n.b=index[n.b];
        if(n.op==DP_SELECT)n.aux=index[n.aux];
        p->nodes[total]=n;p->constants[total++]=p->constants[j];
    }
    p->output=index[p->output];p->count=total;free(used);free(index);
    p->varying = calloc(p->count, 1);
    if (p->varying) {
        for (uint32_t j = 0; j < p->count; ++j) {
            ce_domain_node n = p->nodes[j];
            if (n.op == DP_Z) p->varying[j] = 1;
            else if (n.op != DP_CONST && n.op != DP_C) {
                p->varying[j] = p->varying[n.a];
                if (n.op == DP_ADD || n.op == DP_SUB || n.op == DP_MUL || n.op == DP_DIV || n.op == DP_SELECT || n.op == DP_TEST || n.op == DP_INTEGER || (n.op == DP_ANALYTIC && n.aux == DA_BESSEL)) p->varying[j] |= p->varying[n.b];
                if (n.op == DP_SELECT) p->varying[j] |= p->varying[n.aux];
            }
        }
    }
    return p;
}
void ce_domain_program_free(ce_domain_program *p){
    if(p){
        if (p->vp_valid) {
            acb_clear(p->vp_center);
            acb_clear(p->vp_stepx);
            acb_clear(p->vp_stepy);
            acb_clear(p->vp_inv_stepx);
        }
        free(p->nodes);free(p->constants);free(p->varying);free(p->exp_coeffs);free(p);
    }
}
const ce_domain_node *ce_domain_nodes(const ce_domain_program *p){return p?p->nodes:NULL;}
uint32_t ce_domain_node_count(const ce_domain_program *p){return p?p->count:0;}
uint32_t ce_domain_output(const ce_domain_program *p){return p?p->output:0;}
const char *ce_domain_error(const ce_domain_program *p){return p?p->error:"Domain allocation failed.";}
